### PR TITLE
Add more books

### PR DESCRIPTION
**Pull request by shirshak55**

### CODE REVIEW

**Comment by shirshak55** [comment]
@SoapDev2018 

Soft Ping :)

Please review if possible. If nobody reviews I will commit by tomorrow :)

**Review by SoapDev2018 — COMMENTED** [review]
I went through all the ebooks, and they look good to me!
Please go ahead and merge!

**Review by SoapDev2018 — APPROVED** [review]
Looks good to me!

**Review by SoapDev2018 — APPROVED** [review]
Looks good to me!

**Pull request merged**
